version: ​'​​3'​
	services:
		web:
			build: ​.​
			ports:
				- ​"​​5000:5000"​
			volumes:
				- ​.:/code
			depends_on:
				- postgres

		redis:
			image: ​redis​
		
		postgres:
			image: ​postgres​
			environment:
				POSTGRES_USER=${POSTGRES_USER}
				POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
				POSTGRES_DB: ​SWPDB
			volumes:
				- ./postgres-data/postgres:/var/lib/postgresql/data

		backend:
			build:
				context: .
				dockerfile: ./docker/backend/Dockerfile
			environment:
				- APP_ENV=dev
			depends_on:
				- postgres
				- redis
			ports:
				- "40001:40001"
			volumes:
				- ./backend:/code

		frontend:
			build:
				context: .
				dockerfile: ./docker/frontend/Dockerfile
			environment:
				- APP_ENV=dev
				- APP_BACKEND_URL=backend:40001
				- APP_FRONTEND_PORT=40002
			depends_on:
				- backend
			ports:
				- "40002:40002"
			volumes:
				- ./frontend:/app/src	

		worker:
			build:
				context: .
				dockerfile: ./docker/worker/Dockerfile
			environment:
				- APP_ENV=dev
			depends_on:
				- postgres
				- redis
			volumes:
				- .:/code
