version: ​'​​3'​
	services:
		redis:
			image: ​redis​
		
		postgres:
			image: ​postgres​
			environment:
				POSTGRES_USER=${POSTGRES_USER}
				POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
				POSTGRES_DB: ​SWPDB
			volumes:
				- ./postgres-data/postgres:/var/lib/postgresql/data

		backend:
			build:
				context: backend
				dockerfile: Dockerfile.backend
			environment:
				- APP_ENV=dev
			depends_on:
				- postgres
				- redis
			ports:
				- "40001:40001"
			volumes:
				- ./backend:/code

		frontend:
			build:
				context: frontend
				dockerfile: Dockerfile
			environment:
				- APP_ENV=dev
				- APP_BACKEND_URL=backend:40001
				- APP_FRONTEND_PORT=40002
			depends_on:
				- backend
			ports:
				- "40002:40002"
			volumes:
				- ./frontend:/app/src	

		worker:
			build:
				context: backend
				dockerfile: Dockerfile.worker
			environment:
				- APP_ENV=dev
			depends_on:
				- postgres
				- redis
			volumes:
				- ./backend:/code
