version: '3'
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - servers
  postgres:
    image: postgres:12.1-alpine
    networks:
      - postgres_db
    ports:
      - "5432:5432"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    networks:
      - servers
      - postgres_db
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - APP_BACKEND_URL=backend:5000
      - APP_FRONTEND_PORT=3000
    networks:
      - servers
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src

networks:
  servers:
    driver: bridge
  postgres_db:
    driver: bridge
