version: '3'
services:
  nginx:
    build: ./nginx/
    ports:
      - 81:81
    depends_on:
      - backend
      - frontend
    networks:
      - servers
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    networks:
      - servers
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - APP_BACKEND_URL=backend:5000
      - APP_FRONTEND_PORT=3000
    networks:
      - servers
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src

networks:
  servers:
    driver: bridge
